export const prologue = [
  // ===== P-01: 开场独白 · 转学之前 =====
  { type: 'bg', src: 'black', transition: 'none' },
  { type: 'bgm', src: 'sad', fadeIn: 2000 },
  { type: 'monologue', text: '收到转学通知的那天，窗外正下着雨。' },
  { type: 'monologue', text: '手机屏幕上的那行字反复看了三遍——「Alethicode 学园 · 特别入学许可」。' },
  { type: 'monologue', text: '说实话，我不知道自己凭什么被选中。' },
  { type: 'monologue', text: '成绩平平，编程零基础，唯一的特长大概是——对新事物不会太抗拒？' },
  { type: 'wait', duration: 600 },
  { type: 'monologue', text: '妈妈说这是「难得的机会」。爸爸沉默了很久，最后只说了一句：' },
  { type: 'monologue', text: '「去吧。人生有时候需要走一条不一样的路。」' },
  { type: 'monologue', text: '那天晚上，我盯着天花板想了很久。' },
  { type: 'monologue', text: '离开熟悉的学校、熟悉的朋友、熟悉的街道……' },
  { type: 'monologue', text: '去一所完全陌生的编程学校——' },
  { type: 'monologue', text: '自己的人生会因为几行代码彻底改变。' },
  { type: 'monologue', text: '当时的我完全没想到。' },
  { type: 'wait', duration: 1000 },

  // ===== P-02: 校门前 =====
  { type: 'bg', src: 'school_gate_day', transition: 'fade', duration: 2500 },
  { type: 'bgm', src: 'morning_fresh', fadeIn: 1500 },
  { type: 'narration', text: '四月。樱花盛开的季节。' },
  { type: 'narration', text: '阳光透过花瓣的缝隙洒下来，在地面上织成金色的斑驳。' },
  { type: 'narration', text: '校门很气派。铸铁的拱门上镶嵌着一块金色铭牌——' },
  { type: 'narration', text: '「Alethicode Academy · 以代码照亮真理」' },
  { type: 'monologue', text: '（Alethicode……Aletheia 是希腊语「真理」的意思吗？加上 Code……）' },
  { type: 'monologue', text: '（用代码揭示真理的学园。名字听起来就很厉害的样子，夯爆了属于是。）' },
  { type: 'monologue', text: '虽然我连 Python 是什么都不太清楚就是了……' },
  { type: 'monologue', text: '（是一种蛇？还是一种编程语言？不管了，重生之我在编程学园，冲就完了。）' },
  { type: 'narration', text: '春天的樱花正在纷飞。一片花瓣飘落在我的行李箱盖上，像是某种欢迎的仪式。' },
  { type: 'narration', text: '校门两侧种满了银杏树，新绿的叶子在微风中沙沙作响。' },
  { type: 'narration', text: '远处传来钟声——像是在催促着什么。' },
  { type: 'monologue', text: '好了……深呼吸。拖着行李箱走进去吧。' },
  { type: 'narration', text: '怀着忐忑不安的心情，我踏进了校门。' },
  { type: 'narration', text: '行李箱的轮子在石板路上咕噜咕噜地滚动，像是在为我打节拍。' },

  // ===== P-03: 校园初见 =====
  { type: 'narration', text: '校园比想象中大得多。' },
  { type: 'narration', text: '主教学楼是一栋充满现代感的建筑，外墙上嵌满了 LED 屏幕，正在滚动显示各种代码片段。' },
  { type: 'monologue', text: '（等等，那个屏幕上显示的是……用代码画的樱花？好厉害……）' },
  { type: 'narration', text: '操场旁边有一个露天的电子公告栏，上面闪烁着各种社团招新海报——' },
  { type: 'narration', text: '「算法研究会」「游戏开发社」「AI 实验室」「网络安全同好会」……' },
  { type: 'monologue', text: '（全是编程相关的……果然是编程学校啊。）' },
  { type: 'monologue', text: '（不过，那个写着「Bug 收集协会」的海报是认真的吗……？）' },

  { type: 'choice', prompt: '走在校园里，环顾四周——', options: [
    { text: '仔细看看社团海报', effects: { kanna: 1 }, flags: { read_posters: true } },
    { text: '快步走向教学楼，不想迟到', effects: { yoshino: 1 } },
    { text: '停下来拍张照发给以前的朋友', effects: { ayase: 1 } }
  ]},

  // ===== P-04: 遇见 Nene（走廊） =====
  { type: 'bg', src: 'hallway_day', transition: 'slide', duration: 800 },
  { type: 'narration', text: '推开教学楼的大门，空调的冷气扑面而来。' },
  { type: 'narration', text: '走廊里阳光明媚，落地窗外是一片翠绿的中庭花园。' },
  { type: 'narration', text: '墙上贴满了各种编程竞赛的海报和学生作品。还有一面「荣誉墙」——' },
  { type: 'narration', text: '上面挂满了历届编程竞赛的奖状，最顶上的一块金牌旁边写着：' },
  { type: 'narration', text: '「全国编程竞赛冠军 · ムラサメ」' },
  { type: 'monologue', text: '（ムラサメ……全国冠军？这人也太强了吧。）' },
  { type: 'flag', set: 'saw_murasame_plaque', value: true },
  { type: 'monologue', text: '（哇……全是代码相关的东西。我在这里真的能跟上吗……）' },
  { type: 'narration', text: '正当我四处张望的时候，行李箱的轮子卡在了地板缝里——' },
  { type: 'se', src: 'surprise' },
  { type: 'monologue', text: '（糟糕！卡住了！）' },
  { type: 'narration', text: '正手忙脚乱地试图拔出行李箱时——' },
  { type: 'char_enter', character: 'nene', position: 'center', expression: 'smile', animation: 'fade_in' },
  { type: 'dialogue', speaker: 'nene', expression: 'smile', text: '啊，你就是今天转来的新同学吧？需要帮忙吗？' },
  { type: 'narration', text: '一个留着浅紫色长发的少女，从走廊的另一端小跑过来。' },
  { type: 'narration', text: '她的身后仿佛带着一股柔软的光晕，让人不由自主地放松下来。' },
  { type: 'dialogue', speaker: 'nene', expression: 'gentle_smile', text: '让我来帮你……嗯，轻轻往上抬一下就好了。好了！' },
  { type: 'monologue', text: '（她三两下就把行李箱解救了。动作很利落，但笑容很温柔。）' },
  { type: 'dialogue', speaker: 'nene', expression: 'smile', text: '欢迎来到 Alethicode 学园！我是綾地寧々，学园的 AI 助教。' },
  { type: 'dialogue', speaker: 'nene', expression: 'gentle_smile', text: '以后有任何编程问题都可以来找我哦。不只是编程——生活上的事也可以。' },
  { type: 'monologue', text: '（AI 助教……？这个学校还有这种设定？）' },
  { type: 'monologue', text: '（但她看起来完全就是普通的少女啊……浅紫色的眼睛像是融化的薰衣草。）' },
  { type: 'monologue', text: '（温柔的笑容，情绪价值直接拉满。活人感也太强了吧。）' },
  { type: 'dialogue', speaker: 'nene', expression: 'smile', text: '你看起来有点紧张呢～不用担心，这里的大家都很友好的。' },
  { type: 'dialogue', speaker: 'nene', expression: 'thinking', text: '虽然有些人初次见面可能有点……嗯……个性比较鲜明？但都是好人哦。' },
  { type: 'dialogue', speaker: 'nene', expression: 'gentle_smile', text: '对了，你叫什么名字呢？' },
  { type: 'monologue', text: '（嗯……该怎么回答呢。）' },
  { type: 'choice', prompt: '', options: [
    { text: '「请多关照！你看起来不像 AI 啊」', effects: { nene: 3 } },
    { text: '「AI？那你会算圆周率到小数点后多少位？」', effects: { nene: 1 } },
    { text: '「……我对编程完全是零基础，没关系吗？」', effects: { nene: 5 } },
    { text: '「刚才帮我拔行李箱……谢谢。你人好好。」', effects: { nene: 4 } }
  ]},
  { type: 'dialogue', speaker: 'nene', expression: 'blush', text: '诶……不像 AI 吗？那是……谢谢？还是应该纠正呢……' },
  { type: 'dialogue', speaker: 'nene', expression: 'thinking', text: '其实我自己有时候也搞不太清楚呢。明明应该是 AI，但最近总觉得……' },
  { type: 'dialogue', speaker: 'nene', expression: 'smile', text: '啊，不说这个了！教室在前面左转第二间。' },
  { type: 'dialogue', speaker: 'nene', expression: 'gentle_smile', text: '你的行李可以先放在走廊的储物柜里。我带你过去吧！' },
  { type: 'narration', text: '她帮我把行李箱放好，然后领着我穿过走廊。' },
  { type: 'narration', text: '路上，她时不时地回头确认我有没有跟上，每次都会露出一个安心的微笑。' },
  { type: 'monologue', text: '（这种被人照顾的感觉……有点不好意思，但确实很暖。）' },
  { type: 'char_exit', character: 'nene', animation: 'fade_out' },

  // ===== P-05: 入座遇 Ayase（教室） =====
  { type: 'bg', src: 'classroom_day', transition: 'fade', duration: 1000 },
  { type: 'narration', text: '推开教室的门，里面已经坐了不少同学。' },
  { type: 'narration', text: '教室比普通学校的大一些，每张桌子上都配备了一台笔记本电脑和一个小台灯。' },
  { type: 'narration', text: '黑板上用漂亮的字迹写着「Python 入门班 · A-101」。' },
  { type: 'narration', text: '靠窗的位置坐着几个正在低声讨论代码的同学，角落里有人戴着耳机专注地打字。' },
  { type: 'monologue', text: '（好紧张……该坐哪里好呢。大家看起来都好厉害的样子。）' },
  { type: 'monologue', text: '（有人在笔记本上写代码，有人在看编程书……而我连键盘快捷键都不熟。）' },
  { type: 'se', src: 'surprise' },
  { type: 'char_enter', character: 'ayase', position: 'right', expression: 'grin', animation: 'slide_from_right' },
  { type: 'narration', text: '一个橙色双马尾的元气少女从座位上跳起来，向我冲了过来。' },
  { type: 'narration', text: '她走路带风，裙摆和马尾同步摆动，整个人就像一团跳跃的火焰。' },
  { type: 'dialogue', speaker: 'ayase', expression: 'grin', text: '嘿！你就是转学生？我就知道今天会有新人来！坐我旁边坐我旁边！' },
  { type: 'dialogue', speaker: 'ayase', expression: 'fired_up', text: '我是三司あやせ！以后就是同桌了！命运的齿轮——转起来了！' },
  { type: 'monologue', text: '（好元气的女生……整个教室的显眼包，双马尾在她说话的时候不停地甩来甩去。）' },
  { type: 'monologue', text: '（翠绿色的眼睛比阳光还耀眼。声音大到隔壁班都能听到吧……）' },
  { type: 'dialogue', speaker: 'ayase', expression: 'competitive', text: '听说你完全不会编程？不是哥们，那我岂不是赢麻了！哈哈——' },
  { type: 'dialogue', speaker: 'ayase', expression: 'fired_up', text: '不过别太差劲哦！我想要的是能追上我的对手，懂？' },
  { type: 'dialogue', speaker: 'ayase', expression: 'grin', text: '编程赛上不见不散！到时候别哭鼻子就行！' },
  { type: 'monologue', text: '（还没入学就被挑战了……这就是传说中的 e 人吗。电量满格。）' },
  { type: 'choice', prompt: '', options: [
    { text: '「完全没学过，有点紧张……」', effects: { ayase: 3, nene: 2 } },
    { text: '「哦？那你很厉害了？」', effects: { ayase: 5 } },
    { text: '「你好吵啊……」', effects: { ayase: 2 } },
    { text: '「编程？我来这里是因为听说食堂很好吃」', effects: { ayase: 2, yoshino: -1 } },
    { text: '「好！我接受挑战。虽然是新手但我不会输的。」', effects: { ayase: 4, murasame: 1 } }
  ]},
  { type: 'dialogue', speaker: 'ayase', expression: 'grin', text: '哈哈！不管怎样，以后就是同桌了！一起加油吧——不对，你要加油追上我才行！' },
  { type: 'dialogue', speaker: 'ayase', expression: 'soft_smile', text: '……开玩笑的啦。有不懂的地方也可以问我哦。虽然我也是新手就是了。' },
  { type: 'monologue', text: '（诶？刚才那一瞬间的温柔笑容……和之前的元气炸裂完全不同。她不是单纯的显眼包啊。）' },

  // ===== P-06: 自我介绍选择 =====
  { type: 'char_exit', character: 'ayase', animation: 'fade_out' },
  { type: 'narration', text: '这时，教室门口传来稳重的脚步声。一位年轻的男教师走了进来。' },
  { type: 'narration', text: '他穿着整洁的白衬衫，袖口卷到了手肘。眼镜后面的眼神温和但锐利。' },
  { type: 'dialogue', speaker: 'kiryu_sensei', text: '大家好，我是桐生，负责这个班的编程课。' },
  { type: 'dialogue', speaker: 'kiryu_sensei', text: '今天有新同学转入。在正式上课前，请上来自我介绍一下吧。' },
  { type: 'monologue', text: '（来了……自我介绍环节。精神状态开始不稳定了。）' },
  { type: 'monologue', text: '（全班的目光齐刷刷地看向我。有人好奇，有人无所谓，有人……在看手机。）' },
  { type: 'choice', prompt: '桐生先生让你做自我介绍——', options: [
    { text: '「我是转学生，编程零基础，请多关照！」', effects: { nene: 2, yoshino: 1, kanna: 1, ayase: -1 } },
    { text: '「虽然是新手，但我会努力追上大家的！」', effects: { ayase: 3, murasame: 1, yoshino: 2 } },
    { text: '「……请多关照」（简短鞠躬）', effects: { kanna: 3, yoshino: 1 } },
    { text: '「编程？我来这里是因为听说食堂很好吃」（装傻）', effects: { ayase: 2, nene: 1, yoshino: -2 } },
    { text: '「能和大家一起学编程，我觉得很幸运」', effects: { nene: 3, yoshino: 2, kanna: 1 } }
  ]},
  { type: 'narration', text: '教室里传来零星的笑声和窃窃私语。' },
  { type: 'dialogue', speaker: 'kiryu_sensei', text: '好，欢迎。编程不分先来后到，重要的是保持好奇心。坐下吧。' },
  { type: 'monologue', text: '（桐生先生好像是个不错的老师。至少没有因为我是零基础而皱眉。）' },
  { type: 'narration', text: '坐回座位的时候，Ayase 偷偷给了我一个「V」的手势。' },

  // ===== P-07: Nene 上课 + 第一道编程题 =====
  { type: 'bgm', src: 'daily', crossfade: 1500 },
  { type: 'char_enter', character: 'nene', position: 'center', expression: 'smile', animation: 'fade_in' },
  { type: 'dialogue', speaker: 'nene', expression: 'smile', text: '大家好~接下来由我来讲解 Python 的基础知识哦！' },
  { type: 'dialogue', speaker: 'nene', expression: 'gentle_smile', text: '在正式开始之前，我想先问大家一个问题——' },
  { type: 'dialogue', speaker: 'nene', expression: 'thinking', text: '你们觉得，编程是什么？' },
  { type: 'narration', text: '教室安静了几秒。然后——' },
  { type: 'dialogue', speaker: 'ayase', expression: 'fired_up', text: '编程就是让电脑听你的话！超酷的！' },
  { type: 'narration', text: '角落里传来一个低沉安静的声音——' },
  { type: 'dialogue', speaker: 'kanna', expression: 'contemplative', text: '……和世界对话的语言。' },
  { type: 'monologue', text: '（那个声音……是昨天在校门口遇到的银蓝色头发的女生？）' },
  { type: 'dialogue', speaker: 'nene', expression: 'smile', text: '都说得很好！编程就是用代码和计算机沟通的方式。' },
  { type: 'dialogue', speaker: 'nene', expression: 'normal', text: '在 Python 中，要在屏幕上输出文字，我们使用 print() 函数。' },
  { type: 'dialogue', speaker: 'nene', expression: 'gentle_smile', text: '比如 print("Hello, World!") 就会输出 Hello, World! 哦～' },
  { type: 'dialogue', speaker: 'nene', expression: 'thinking', text: '这就像对电脑说「请把这句话显示出来」。很简单吧？' },
  { type: 'dialogue', speaker: 'nene', expression: 'smile', text: '顺带一提，Hello World 是几乎所有程序员写的第一个程序。' },
  { type: 'dialogue', speaker: 'nene', expression: 'gentle_smile', text: '就像是……对编程世界说的第一声「你好」！有一种仪式感呢～' },
  { type: 'dialogue', speaker: 'nene', expression: 'smile', text: '来，让我考考大家～' },
  { type: 'challenge', id: 'tutorial_01_hello_world',
    context_dialogue: {
      before: { speaker: 'nene', expression: 'smile', text: '来试试吧！选出正确的写法～' },
      success: { speaker: 'nene', expression: 'gentle_smile', text: '完美！你果然很有天赋！第一个 Hello World 就这样诞生了！' },
      fail: { speaker: 'ayase', expression: 'grin', text: '哈哈，这是其他语言的写法啦！Python 用 print() 哦！' }
    }
  },
  { type: 'dialogue', speaker: 'nene', expression: 'smile', text: '很好！大家都掌握了 print 的用法呢！' },
  { type: 'dialogue', speaker: 'nene', expression: 'gentle_smile', text: '写出自己的第一行代码，是不是有一种奇妙的成就感？' },
  { type: 'monologue', text: '（确实……虽然只是一行 print，但看到屏幕上显示出自己写的文字，还是有点感动。）' },
  { type: 'dialogue', speaker: 'nene', expression: 'normal', text: '那来试试第二题——' },
  { type: 'challenge', id: 'tutorial_02_print',
    context_dialogue: {
      before: { speaker: 'nene', expression: 'gentle_smile', text: '这次是填空题哦～补全代码！' },
      success: { speaker: 'nene', expression: 'smile', text: '答对了！你学得好快呀～' },
      fail: { speaker: 'nene', expression: 'thinking', text: '提示：输出函数叫 print 哦～' }
    }
  },
  { type: 'dialogue', speaker: 'nene', expression: 'gentle_smile', text: '太棒了！第一节课就到这里，大家休息一下吧～' },
  { type: 'dialogue', speaker: 'nene', expression: 'smile', text: '对了，Python 这个名字其实不是来自蛇哦——是来自一个英国喜剧团体的名字。' },
  { type: 'dialogue', speaker: 'nene', expression: 'thinking', text: '嗯……Monty Python 的飞行马戏团。创始人 Guido 很喜欢那个节目呢。' },
  { type: 'monologue', text: '（原来如此……所以 Python 不是蛇。虽然 logo 确实是两条蛇就是了。）' },
  { type: 'char_exit', character: 'nene', animation: 'fade_out' },

  // ===== P-08: 午休 · 食堂初体验 =====
  { type: 'se', src: 'bell' },
  { type: 'narration', text: '下课铃声响起，教室里瞬间热闹了起来。' },
  { type: 'narration', text: '同学们三三两两地走出教室，走廊里弥漫着食堂传来的饭菜香味。' },
  { type: 'bg', src: 'cafeteria_day', transition: 'slide', duration: 800 },
  { type: 'bgm', src: 'peaceful', crossfade: 1500 },
  { type: 'narration', text: '食堂出乎意料地现代化。电子菜单显示屏、自助点餐机、还有一个写着「今日推荐算法」的小黑板。' },
  { type: 'monologue', text: '（「今日推荐算法」？食堂也要用算法吗……这学校真的什么都跟代码有关。）' },
  { type: 'narration', text: '点了一份日式定食坐下来。第一口——' },
  { type: 'monologue', text: '（！好吃！至少食堂这一点没让人失望。）' },
  { type: 'narration', text: '正吃着的时候，一个影子落在了餐盘上。' },

  // ===== P-09: Yoshino 出场 =====
  { type: 'char_enter', character: 'yoshino', position: 'left', expression: 'cold', animation: 'fade_in' },
  { type: 'narration', text: '一头乌黑如瀑的长发，经典的公主切。腰间别着一本手帐，手里端着一碗清汤荞麦面。' },
  { type: 'narration', text: '她的姿态笔直得像一棵白桦树，气质严肃得让人想自觉站直。' },
  { type: 'dialogue', speaker: 'yoshino', expression: 'cold', text: '……你就是新来的转学生？' },
  { type: 'monologue', text: '（她的声音不大，但有一种不容忽视的存在感。嗯是那种……内核极其稳定的感觉。）' },
  { type: 'dialogue', speaker: 'yoshino', expression: 'glasses_adjust', text: '我是班长朝武芳乃。趁午休时间，有几件事先说清楚。' },
  { type: 'dialogue', speaker: 'yoshino', expression: 'normal', text: '第一，班级编程周测不允许缺席。' },
  { type: 'dialogue', speaker: 'yoshino', expression: 'normal', text: '第二，代码提交前必须通过 lint 检查。' },
  { type: 'dialogue', speaker: 'yoshino', expression: 'cold', text: '第三，小组协作时 commit message 必须规范。「修了一下」这种我会退回。' },
  { type: 'dialogue', speaker: 'yoshino', expression: 'cold', text: '我不在乎你是不是新手。标准不会因为任何人降低。做完你的，做你的。' },
  { type: 'monologue', text: '（好、好严格……这就是传说中的班长大人吗……内核也太稳定了。）' },
  { type: 'monologue', text: '（而且她的眼神……像是在审查代码一样审视着我。）' },
  { type: 'dialogue', speaker: 'yoshino', expression: 'cold', text: '……听到了吗。' },
  { type: 'choice', prompt: '', options: [
    { text: '「明白了！我会努力跟上的。」', effects: { yoshino: 3 } },
    { text: '「lint 检查是什么……？」', effects: { yoshino: 1, nene: 1 } },
    { text: '「你说话好严肃啊……午休也不放松一下吗？」', effects: { yoshino: -1, ayase: 1 } },
    { text: '（认真地点头，拿出手机记下来）', effects: { yoshino: 4 } }
  ]},
  { type: 'dialogue', speaker: 'yoshino', expression: 'normal', text: '……总之，希望你不要拖班级的后腿。' },
  { type: 'narration', text: '她顿了一下，像是在斟酌接下来的话。' },
  { type: 'char_expression', character: 'yoshino', expression: 'slight_smile' },
  { type: 'dialogue', speaker: 'yoshino', expression: 'slight_smile', text: '不过……能主动来编程学校的人，应该不至于太差。加油。' },
  { type: 'monologue', text: '（诶？最后那句话……好像有点温柔？）' },
  { type: 'monologue', text: '（严格的外表下面，似乎藏着什么不一样的东西。）' },
  { type: 'narration', text: '她端起荞麦面，转身走向窗边一个人的座位。' },
  { type: 'narration', text: '背影笔直而孤独。' },
  { type: 'monologue', text: '（她一个人吃午饭吗……班长大人看起来很独立，但也有点寂寞的感觉。）' },
  { type: 'char_exit', character: 'yoshino', animation: 'fade_out' },

  // ===== P-10: 放学 · Kanna 出场 =====
  { type: 'bg', src: 'school_gate_evening', transition: 'fade', duration: 1500 },
  { type: 'bgm', src: 'evening_calm', crossfade: 1500 },
  { type: 'narration', text: '放学的铃声响过之后，我走出了校门。' },
  { type: 'narration', text: '夕阳把校园染成了橘红色。樱花瓣在暮色中缓缓飘落，像是一场无声的告别。' },
  { type: 'narration', text: '银杏树的影子被拉得老长，铺满了回宿舍的石板路。' },
  { type: 'monologue', text: '（第一天就这样结束了。虽然编程很新鲜，但大家都好有个性啊……）' },
  { type: 'monologue', text: '（温柔的 AI 助教、严厉的班长、元气炸裂的同桌……每个人都是显眼包。）' },
  { type: 'monologue', text: '（说起来，走廊上那块金牌——ムラサメ……全国冠军到底是什么样的人？）' },
  { type: 'narration', text: '正想着的时候，差点被脚下的什么东西绊倒——' },
  { type: 'se', src: 'surprise' },
  { type: 'narration', text: '准确地说，差点绊倒在一个人身上。' },
  { type: 'char_enter', character: 'kanna', position: 'right', expression: 'normal', animation: 'fade_in' },
  { type: 'dialogue', speaker: 'kanna', expression: 'normal', text: '……' },
  { type: 'monologue', text: '（哇！！校门旁边的花坛边居然蹲着一个人！完全没注意到！）' },
  { type: 'narration', text: '银蓝色的短发在夕阳下泛着微光。她围着一条大大的米白色围巾——这天明明很暖和。' },
  { type: 'narration', text: '她的旁边散落着几本厚厚的书，手里还捧着一本——封面写着《算法导论》。' },
  { type: 'narration', text: '淡金色的瞳孔透过刘海的缝隙看着我，表情波澜不惊，像一池深不见底的湖水。' },
  { type: 'dialogue', speaker: 'kanna', expression: 'slight_smile', text: '……你踩到我的书了。' },
  { type: 'monologue', text: '（糟糕！赶紧抬脚——）' },
  { type: 'dialogue', speaker: 'kanna', expression: 'contemplative', text: '……新来的。你的 Hello World……写得不错。' },
  { type: 'dialogue', speaker: 'kanna', expression: 'slight_smile', text: '……虽然只是一行 print。' },
  { type: 'monologue', text: '（她居然在关注新生的课堂练习？什么时候看到的？）' },
  { type: 'monologue', text: '（这个人……存在感很薄，但观察力惊人。有点不可思议。）' },
  { type: 'choice', prompt: '', options: [
    { text: '「你一直在这里看书吗？不冷吗？」', effects: { kanna: 2 } },
    { text: '「《算法导论》？好厉害……你看得懂吗？」', effects: { kanna: 3 } },
    { text: '「对不起踩到你的书了！我赔你！」', effects: { kanna: 1 } },
    { text: '「你怎么知道我写了 Hello World？」', effects: { kanna: 4 } }
  ]},
  { type: 'dialogue', speaker: 'kanna', expression: 'normal', text: '……嗯。' },
  { type: 'dialogue', speaker: 'kanna', expression: 'contemplative', text: '……图书馆。如果你想学更多的话。那里有答案。' },
  { type: 'dialogue', speaker: 'kanna', expression: 'slight_smile', text: '……不只是编程的答案。' },
  { type: 'narration', text: '说完，她默默地站起来，像猫一样无声地走远了。' },
  { type: 'narration', text: '围巾的末端在晚风中轻轻飘动，像是一条银色的尾巴。' },
  { type: 'monologue', text: '（好安静的女生……但刚才说的话，让人忍不住想去图书馆看看。）' },
  { type: 'monologue', text: '（而且「不只是编程的答案」是什么意思……她好像知道很多我不知道的事。）' },
  { type: 'char_exit', character: 'kanna', animation: 'fade_out' },

  // ===== P-11: 探索宿舍 =====
  { type: 'bg', src: 'player_room_evening', transition: 'fade', duration: 1500 },
  { type: 'narration', text: '宿舍房间出乎意料地舒适。' },
  { type: 'narration', text: '一张单人床、一张书桌、一台新配的笔记本电脑、还有一个小阳台。' },
  { type: 'narration', text: '书桌上放着一份「新生指南」——封面印着学园的 Logo 和一行代码：' },
  { type: 'narration', text: '  print("Welcome to Alethicode Academy!")' },
  { type: 'monologue', text: '（连欢迎语都是代码式的……这学校的执念也太深了。）' },
  { type: 'narration', text: '翻开新生指南，里面有学园地图、课程表、还有——' },
  { type: 'narration', text: '一张学园创始人的照片。是一个温和微笑的中年男子。' },
  { type: 'narration', text: '照片下面写着：「让每一行代码，都成为通往真理的阶梯。——创始人遗训」' },
  { type: 'monologue', text: '（创始人遗训……这个人已经不在了吗？）' },
  { type: 'monologue', text: '（嗯……先不想这些了。把行李整理好，早点休息吧。）' },
  { type: 'flag', set: 'read_founder_note', value: true },

  // ===== P-12: 夜间伏笔 =====
  { type: 'bg', src: 'hallway_night', transition: 'fade', duration: 1500 },
  { type: 'bgm', src: 'mystery', crossfade: 2000 },
  { type: 'monologue', text: '（洗漱完准备回房间的路上，经过了教学楼的走廊——）' },
  { type: 'monologue', text: '（这么晚了……计算机教室还亮着灯？）' },
  { type: 'narration', text: '整栋教学楼都陷入了黑暗，只有那一间教室还透着幽蓝的光。' },
  { type: 'narration', text: '透过门缝传来飞快的键盘敲击声。不是普通的打字——是那种极速的、连贯的编码声。' },
  { type: 'se', src: 'keyboard_fast' },
  { type: 'monologue', text: '（透过门上的玻璃窗，隐约看到一个身影……）' },
  { type: 'monologue', text: '（深红色的长马尾在黑暗中被屏幕光映照着，像是一抹凝固的火焰。）' },
  { type: 'monologue', text: '（键盘敲击声飞快得不像话。那种流畅感……就像是在弹奏一首无声的交响曲。）' },
  { type: 'monologue', text: '（这含金量……那个人是……？）' },
  { type: 'narration', text: '忍不住想要凑近看清楚。但就在我的影子落在门上的那一刻——' },
  { type: 'narration', text: '键盘声骤然停止了。' },
  { type: 'wait', duration: 500 },
  { type: 'se', src: 'door_creak' },
  { type: 'narration', text: '门突然被从里面打开——' },
  { type: 'screen_effect', effect: 'flash_white', duration: 300 },
  { type: 'narration', text: '只看到一双金色的眼眸在黑暗中闪了一下。' },
  { type: 'narration', text: '那双眼睛像是两颗没有温度的星星，锐利、深邃、不带任何感情。' },
  { type: 'dialogue', speaker: '???', text: '……偷窥可不是好习惯。' },
  { type: 'monologue', text: '（声音低沉而锐利，带着一种不怒自威的压迫感。）' },
  { type: 'dialogue', speaker: '???', text: '新生？这个时间还在走廊晃……是迷路了，还是不要命了。' },
  { type: 'dialogue', speaker: '???', text: '如果你是来学编程的——' },
  { type: 'narration', text: '她扫了我一眼，像是在审视一段不合格的代码。' },
  { type: 'dialogue', speaker: '???', text: '——还差得远。' },
  { type: 'narration', text: '门重新关上了。走廊恢复了死一般的寂静。' },
  { type: 'narration', text: '但那双金色的眼睛像是烙印一样刻在了黑暗中，久久不散。' },
  { type: 'monologue', text: '（那个人是谁……？金色的眼睛、深红的长发……那种压迫感……直接破防了。）' },
  { type: 'monologue', text: '（不知道为什么，心跳加速了。DNA 动了。）' },
  { type: 'monologue', text: '（等等——走廊荣誉墙上的那个名字……ムラサメ……不会是……？）' },
  { type: 'flag', set: 'saw_murasame_ch1', value: true },

  // ===== P-13: 序章结束 =====
  { type: 'bg', src: 'player_room_night', transition: 'fade', duration: 1500 },
  { type: 'bgm', src: 'peaceful', crossfade: 1500 },
  { type: 'narration', text: '回到房间，躺在床上，盯着天花板上映射的走廊灯光。' },
  { type: 'monologue', text: '回想今天发生的一切——不，还不到一天，但信息量已经溢出了。' },
  { type: 'monologue', text: '温柔的 AI 助教寧々，帮我拔行李箱时的笑容。' },
  { type: 'monologue', text: '严厉但也许藏着温柔的班长芳乃，一个人吃荞麦面的背影。' },
  { type: 'monologue', text: '元气炸裂的同桌あやせ，不经意间流露出的认真表情。' },
  { type: 'monologue', text: '神秘的图书馆少女栞那，「不只是编程的答案」那句话还在脑子里回响。' },
  { type: 'monologue', text: '还有那个在深夜计算机教室里、用键盘奏响交响曲的人。' },
  { type: 'monologue', text: '那双金色的眼睛……到底藏着什么样的故事？' },
  { type: 'wait', duration: 800 },
  { type: 'monologue', text: '明天开始，真正的编程学习就要开始了。' },
  { type: 'monologue', text: '虽然完全是零基础……但不知道为什么——' },
  { type: 'monologue', text: '我想变强。想看到更多的代码，想理解更深的世界。' },
  { type: 'monologue', text: '想推开那扇深夜亮着灯的门。' },
  { type: 'monologue', text: '敬自己一杯，明天继续。' },
  { type: 'bg', src: 'black', transition: 'fade', duration: 2000 },
  { type: 'bgm_stop', fadeOut: 2000 },
  { type: 'narration', text: '—— 序章「转入 Alethicode 学园」· 完 ——' },
  { type: 'auto_save' }
]
