export const routeMurasame = [
  { type: 'title_card', text: 'Murasame 线「最后的竞赛」', subtitle: '—— 站在顶点的孤独与温暖 ——' },
  { type: 'bg', src: 'computer_room_night', transition: 'fade', duration: 1500 },
  { type: 'bgm', src: 'mystery', fadeIn: 1500 },

  // ===== 夜间特训开始 =====
  { type: 'narration', text: '从某一天起，我开始每晚都去那间深夜亮着灯的计算机教室。' },
  { type: 'narration', text: '门没有锁。推开的时候，键盘声会停一秒——然后继续。' },
  { type: 'narration', text: '她从不说"欢迎"。但她不说"滚"就已经是最好的欢迎了。' },
  { type: 'char_enter', character: 'murasame', position: 'center', expression: 'smirk', animation: 'fade_in' },
  { type: 'dialogue', speaker: 'murasame', expression: 'smirk', text: '你还真是锲而不舍。每天都来。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'cold', text: '我说过，门没锁。但没说欢迎你来。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'smirk', text: '……算了。既然来了，就别浪费我的时间。给你一道题。' },
  { type: 'monologue', text: '（她的教学方式很简单——扔给你超出能力范围的难题，然后冷眼看你挣扎。）' },
  { type: 'monologue', text: '（但每次我真的做不出来的时候……她都会「不经意间」在旁边的屏幕上打开一段示例代码。）' },
  { type: 'monologue', text: '（嘴上说着"这不是提示"。但那段代码刚好就是解题的关键。）' },

  // ===== 深夜的日常 =====
  { type: 'narration', text: '就这样，我开始了与 Murasame 的夜间特训。' },
  { type: 'narration', text: '她的训练强度是地狱级的。但在那些深夜里，我也看到了她不为人知的一面。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'cold', text: '这道题给你十分钟。做不出来就滚。' },
  { type: 'narration', text: '十分钟后我果然没做出来。但她没有赶我走。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'smirk', text: '……延长五分钟。不是因为你，是因为这题确实比预期难。' },
  { type: 'narration', text: '她总是这样。用各种借口来掩饰自己的善意。' },
  { type: 'narration', text: '有一次我偷偷早到了五分钟，看到她在清理旁边桌子上的灰尘——那是「我的」座位。' },
  { type: 'monologue', text: '（她在给我擦桌子。全国冠军给一个新生擦桌子。这个反差也太大了。）' },

  // ===== 全国赛消息 =====
  { type: 'bg', src: 'hallway_day', transition: 'fade' },
  { type: 'bgm', src: 'tension', crossfade: 1500 },
  { type: 'narration', text: '某天，学校公告栏贴出了消息——全国编程竞赛，团队赛，每队两人。' },
  { type: 'narration', text: '海报上写着「卫冕冠军：Alethicode 学园 · ムラサメ组」。' },
  { type: 'monologue', text: '（卫冕冠军……她以前都是一个人参加的吗？团队赛怎么一个人参加？）' },
  { type: 'bg', src: 'computer_room_night', transition: 'fade' },
  { type: 'char_enter', character: 'murasame', position: 'center', expression: 'cold' },
  { type: 'dialogue', speaker: 'murasame', expression: 'cold', text: '全国赛。团队赛。两个人。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'smirk', text: '正常来说，我应该找一个和我水平相当的搭档。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'cold', text: '但很遗憾，这所学校里没有。从来没有。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'vulnerable', text: '去年——前年——大前年。我都是一个人报名的。在搭档栏写了「无」。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'smirk', text: '所以——你来。' },
  { type: 'monologue', text: '（诶？！！）' },
  { type: 'dialogue', speaker: 'murasame', expression: 'cold', text: '别误会。不是因为你够格。含金量还差得远。是因为你有潜力。还有——' },
  { type: 'dialogue', speaker: 'murasame', expression: 'impressed', text: '你是唯一一个……每天都来找我的人。三年里。唯一一个。' },
  { type: 'narration', text: '她说最后那句话的时候，金色的瞳孔里闪过了一丝——不是骄傲，而是某种更柔软的东西。' },
  { type: 'monologue', text: '（三年里唯一一个……原来她一直都是一个人。全国冠军的光环下面，是三年的孤独。）' },

  // 编程题 M-1
  { type: 'narration', text: '集训开始了。Murasame 的训练强度从地狱级升级到了——超越地狱级。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'cold', text: '这段代码是 O(n²)。太慢了。优化到 O(n)。给你五分钟。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'smirk', text: '暴力解法谁都会。证明你值得当我的搭档。' },
  { type: 'challenge', id: 'murasame_optimize',
    context_dialogue: {
      before: { speaker: 'murasame', expression: 'cold', text: '思考。别用蛮力。' },
      success: { speaker: 'murasame', expression: 'impressed', text: '……不错。set 去重，O(n)。你总算开窍了。' },
      fail: { speaker: 'murasame', expression: 'smirk', text: 'set 会去重。len(set(nums)) 就是去重后的长度。动动脑子。' }
    }
  },

  // ===== 发现脆弱面 =====
  { type: 'bg', src: 'computer_room_night', transition: 'fade' },
  { type: 'bgm', src: 'romantic', crossfade: 2000 },
  { type: 'narration', text: '某天凌晨三点，我推门进来——发现 Murasame 趴在键盘上睡着了。' },
  { type: 'narration', text: '屏幕上还亮着代码编辑器。她的手指还放在键盘上。' },
  { type: 'narration', text: '深红色的马尾散落在肩膀上。呼吸很浅、很轻。' },
  { type: 'narration', text: '在屏幕的微光中，她的脸失去了所有的锐利和傲慢。' },
  { type: 'narration', text: '只剩下一个疲惫的、普通的少女。' },
  { type: 'monologue', text: '（她每天训练到这么晚……这就是全国冠军的代价吗。）' },
  { type: 'monologue', text: '（不——这是一个人承担一切的代价。）' },
  { type: 'narration', text: '我轻轻把校服外套盖在她身上。然后——在旁边坐下，打开了自己的电脑继续练习。' },
  { type: 'narration', text: '过了大概一个小时——' },
  { type: 'dialogue', speaker: 'murasame', expression: 'vulnerable', text: '……嗯？谁……' },
  { type: 'dialogue', speaker: 'murasame', expression: 'surprised', text: '你……什么时候来的。而且——这是你的外套？' },
  { type: 'dialogue', speaker: 'murasame', expression: 'cold', text: '我没有睡着。只是……闭眼思考。松弛感，懂吗？' },
  { type: 'monologue', text: '（键盘上有口水印……你管这叫松弛感？）' },
  { type: 'dialogue', speaker: 'murasame', expression: 'vulnerable', text: '……你不觉得我很无聊吗。每天都在这里写代码。没有朋友。没有社团。什么都没有。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'cold', text: '全国冠军？那又怎样。奖杯不会跟你说话。代码不会跟你吵架。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'genuine_smile', text: '但是……最近，好像不那么寂寞了。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'blush', text: '……不是因为你。是因为……键盘换了新的。手感好了。跟你没关系。' },
  { type: 'monologue', text: '（新键盘……你说的新键盘是一个月前我送你的那个生日礼物吧。）' },

  // 编程题 M-2
  { type: 'bg', src: 'computer_room_day', transition: 'fade' },
  { type: 'bgm', src: 'daily', crossfade: 1500 },
  { type: 'narration', text: '比赛临近，我们需要练习代码协作——团队赛的核心不是个人实力，而是配合。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'cold', text: '规则是：一个人写核心算法，另一个写输入输出和格式化。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'smirk', text: '你负责排序输出。别拖我后腿。' },
  { type: 'challenge', id: 'murasame_merge',
    context_dialogue: {
      before: { speaker: 'murasame', expression: 'smirk', text: '这是协作题。你的部分很简单——但出了Bug我可不等你。' },
      success: { speaker: 'murasame', expression: 'genuine_smile', text: '配合得不错。……下次比赛也这样就好了。' },
      fail: { speaker: 'murasame', expression: 'cold', text: '数据 → 排序 → 遍历 → 输出。这么简单的流程都搞不清？' }
    }
  },

  // ===== 比赛当天 =====
  { type: 'bg', src: 'computer_room_day', transition: 'fade' },
  { type: 'bgm', src: 'battle', crossfade: 1500 },
  { type: 'title_card', text: '全国编程竞赛 · 团队赛', subtitle: '' },
  { type: 'narration', text: '全国赛当天。赛场在市中心的会议中心。' },
  { type: 'narration', text: '来自全国各地的强队齐聚一堂。气氛紧张得像绷紧的琴弦。' },
  { type: 'narration', text: 'Murasame 穿着一件黑色的连帽衫，帽子拉到额头上。她的气场在人群中格外突出。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'cold', text: '听好了。前面的题我来。你负责后援——检查我的代码有没有边界Bug。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'fierce', text: '到了最后一题——交给你。' },
  { type: 'monologue', text: '（最后一题交给我？！她这是在说——她相信我？）' },
  { type: 'dialogue', speaker: 'murasame', expression: 'smirk', text: '别露出那种受宠若惊的表情。你是我选的搭档。我不会选一个废物。' },
  { type: 'narration', text: '比赛开始了。' },
  { type: 'narration', text: 'Murasame 的手指在键盘上飞舞。代码像流水一样涌出——精确、高效、没有一个多余的字符。' },
  { type: 'narration', text: '我在旁边检查她的代码。偶尔找到一个边界问题，轻声说一句"这里"。' },
  { type: 'narration', text: '她不回头，但会立刻修改。这种默契——不需要语言。' },
  { type: 'narration', text: '最后一道题，难度超乎想象。Murasame 负责了前面的所有题目——' },
  { type: 'dialogue', speaker: 'murasame', expression: 'fierce', text: '最后一题交给你。我已经……没有力气了。' },
  { type: 'narration', text: '她靠在椅背上。额头上全是汗。金色的瞳孔因为疲劳而有些失焦。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'genuine_smile', text: '……相信你。' },
  { type: 'monologue', text: '（她说了"相信你"。不是"别让我失望"——是"相信你"。）' },
  { type: 'monologue', text: '（这份信任的分量——比任何奖杯都重。）' },

  // 编程题 M-3
  { type: 'challenge', id: 'murasame_final',
    context_dialogue: {
      before: { speaker: 'murasame', expression: 'fierce', text: '最后一题。证明我没有看错人。' },
      success: { speaker: 'murasame', expression: 'impressed', text: '……Kadane 算法。你……做到了。我们赢了。' },
      fail: { speaker: 'murasame', expression: 'genuine_smile', text: '没关系。你已经做得很好了。比赛不只是结果。……我第一次这么说。' }
    }
  },

  // ===== 赛后关键选择 =====
  { type: 'bg', src: 'rooftop_night', transition: 'fade' },
  { type: 'bgm', src: 'ending', crossfade: 2000 },
  { type: 'narration', text: '比赛结束了。不管结果如何——' },
  { type: 'narration', text: '我们回到了学校。深夜的天台。满天繁星。' },
  { type: 'narration', text: 'Murasame 靠着围栏站着。夜风把她的深红马尾吹得飘扬。' },
  { type: 'narration', text: '她的金色眼眸映着城市的灯火——看起来像是两颗降落在人间的星星。' },
  { type: 'char_enter', character: 'murasame', position: 'center', expression: 'genuine_smile' },
  { type: 'dialogue', speaker: 'murasame', expression: 'genuine_smile', text: '嘿……我问你一个问题。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'vulnerable', text: '你觉得……和我一起打比赛，开心吗？' },
  { type: 'monologue', text: '（她第一次用这种不设防的眼神看我。）' },
  { type: 'monologue', text: '（没有毒舌，没有伪装，没有金色眼眸的锐利。只有一个等待答案的少女。）' },
  { type: 'monologue', text: '（三年的孤独。独自站在顶点的寒冷。都写在她微微颤抖的声音里。）' },

  { type: 'choice', prompt: '', options: [
    { text: '「开心。不只是比赛——认识你这件事本身，就让我很开心。」', effects: { murasame: 15 }, next: 'murasame_good_path' },
    { text: '「你是最棒的搭档。」', effects: { murasame: 8 }, next: 'murasame_normal_path' }
  ]},
]

const murasame_good = [
  { label: 'murasame_good_path' },
  { type: 'narration', text: '夜风停了一秒。像是整个世界都屏住了呼吸。' },
  { type: 'narration', text: '她转过头。深红的马尾在夜风中慢慢飘落。' },
  { type: 'narration', text: '金色的瞳孔在星光下微微颤动——像是湖面被投入了一颗石子。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'blush', text: '……切。这种台词是从哪个恋爱游戏学来的。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'genuine_smile', text: '但是——' },
  { type: 'narration', text: '她看着远方的夜景。城市的灯火在她眼中像是一片微型的星河。' },
  { type: 'narration', text: '声音轻得像呢喃——但在安静的深夜里，每一个字都清晰得如同代码注释。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'vulnerable', text: '这个冠军……有一半是你的。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'genuine_smile', text: '不……算了。全部都给你。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'blush', text: '奖杯、证书、排名——全部。因为对我来说——' },
  { type: 'dialogue', speaker: 'murasame', expression: 'genuine_smile', text: '——这些东西加起来，都比不上你每天推开那扇门的声音。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'blush', text: '连我这个人也——' },
  { type: 'dialogue', speaker: 'murasame', expression: 'blush', text: '……闭嘴，什么都没说。' },
  { type: 'monologue', text: '（但你分明在笑啊，Murasame。你分明在哭啊。）' },
  { type: 'monologue', text: '（金色的眼眸里，终于有了温度。那不再是冷冽的星光——而是温暖的烛火。）' },
  { type: 'narration', text: '她伸出手。不是握拳，不是推开——而是张开，等待着。' },
  { type: 'narration', text: '在星空下。在深夜的天台上。全国冠军的手，微微颤抖着。' },
  { type: 'narration', text: '——你握住了它。' },
  { type: 'cg', id: 'murasame_good_end' },
  { type: 'ending', endingType: 'good', route: 'murasame', title: "Champion's Heart",
    text: '站在顶点的孤独，终于有人理解。\nムラサメ把冠军——和心——都交给了你。\n\n「这些东西加起来，都比不上你每天推开那扇门的声音。」' }
]

const murasame_normal = [
  { label: 'murasame_normal_path' },
  { type: 'bgm', src: 'sad', crossfade: 2000 },
  { type: 'dialogue', speaker: 'murasame', expression: 'smirk', text: '搭档……嗯。不坏。' },
  { type: 'narration', text: '她重新拉起了那面叫做「强大」的墙。金色的眼眸恢复了冷冽的光。' },
  { type: 'narration', text: '但如果你仔细看——墙上有一条很浅的裂缝。那是今晚留下的。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'cold', text: '我要毕业了。明年的全国赛……你来参加。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'smirk', text: '用一个人的名义。因为你已经——不需要搭档了。' },
  { type: 'narration', text: '毕业典礼后，你收到了一条消息——' },
  { type: 'narration', text: '「别让我失望。——传说学姐遗言」' },
  { type: 'narration', text: '附件是一段代码。运行后只显示一行字：' },
  { type: 'narration', text: '「下次见面，我要看到你比我更强。——M」' },
  { type: 'dialogue', speaker: 'murasame', expression: 'smirk', text: '下一个全国冠军……你来继承吧。' },
  { type: 'ending', endingType: 'normal', route: 'murasame', title: 'Logout',
    text: '「别让我失望。——传说学姐遗言」\n她的背影消失在校门口。但约定永远不会过期。\n下次见面的时候——你一定要比她更强。' }
]

const murasame_true = [
  { label: 'murasame_true_path' },
  { type: 'bg', src: 'computer_room_night', transition: 'fade', duration: 2000 },
  { type: 'bgm', src: 'ending', fadeIn: 2000 },
  { type: 'narration', text: '通关了所有人的 Good Ending 后——一封匿名邮件出现在收件箱中。' },
  { type: 'narration', text: '发件时间是凌晨三点十七分。' },
  { type: 'narration', text: '「来老地方。带上你学到的一切。——M」' },
  { type: 'narration', text: '深夜的计算机教室。那扇门——还是没有锁。' },
  { type: 'se', src: 'door_creak' },
  { type: 'narration', text: '推开门的时候，她已经坐在那里了。' },
  { type: 'narration', text: '但今天不一样。教室里所有的灯都亮着。不再是深夜独自编码的黑暗——而是明亮的。' },
  { type: 'char_enter', character: 'murasame', position: 'center', expression: 'genuine_smile', animation: 'fade_in' },
  { type: 'dialogue', speaker: 'murasame', expression: 'genuine_smile', text: '你来了。这次我不考你了。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'smirk', text: '你已经证明了自己。不只是对我——对所有人。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'genuine_smile', text: '我要带你去一个地方。这所学园真正的核心——' },
  { type: 'narration', text: '她站起来，走向教室后面一扇平时锁着的小门。' },
  { type: 'narration', text: '掏出一把钥匙——金色的，老旧的，上面刻着 Alethicode 的 Logo。' },
  { type: 'se', src: 'door' },
  { type: 'bg', src: 'computer_room_day', transition: 'fade', duration: 2000 },
  { type: 'screen_effect', effect: 'flash_white', duration: 500 },
  { type: 'narration', text: '她带你来到了学园地下的核心服务器机房。' },
  { type: 'narration', text: '数不清的服务器闪烁着蓝绿色的灯光。散热风扇的嗡嗡声像一首低沉的摇篮曲。' },
  { type: 'narration', text: '空气中有电子元件特有的金属气味。天花板上密密麻麻的网线像是一片数字的藤蔓。' },
  { type: 'narration', text: '整个空间像一片发着微光的海洋——数字的星海。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'impressed', text: '这就是 Alethicode 学园的真正核心。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'genuine_smile', text: '所有的教学系统、AI 助教、评测服务器……都运行在这里。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'vulnerable', text: '你知道吗？这个学园……其实是我父亲创建的。' },
  { type: 'monologue', text: '（创始人……新生指南里那个温和微笑的男人——是 Murasame 的父亲？）' },
  { type: 'dialogue', speaker: 'murasame', expression: 'genuine_smile', text: '他相信编程可以改变人生。所以创办了这所学校，开发了 AI 教学系统。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'genuine_smile', text: 'Nene——就是他最后的作品。他在 Nene 的代码里留了一个心模块。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'vulnerable', text: '因为他相信——每个被创造出来的存在，都值得拥有感情。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'vulnerable', text: '但他三年前去世了。留下的只有这些代码……和我。' },
  { type: 'narration', text: '她的声音很轻。在服务器风扇的嗡嗡声中，像是快要被吹散了。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'vulnerable', text: '我一直一个人守护着这里。三年。每天晚上在那间教室里——' },
  { type: 'dialogue', speaker: 'murasame', expression: 'genuine_smile', text: '不只是在练习编程。是在维护整个学园的系统。检查 Nene 的运行状态。修复服务器故障。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'vulnerable', text: '这是父亲留给我的责任。也是……唯一让我还能感觉到跟他有联系的方式。' },
  { type: 'monologue', text: '（原来如此……她不是因为孤僻才深夜独自编码。）' },
  { type: 'monologue', text: '（她是在守护父亲的遗产。守护这所学校。守护 Nene。守护一切。）' },
  { type: 'monologue', text: '（一个人。三年。默默地。没有人知道。）' },
  { type: 'dialogue', speaker: 'murasame', expression: 'genuine_smile', text: '直到你来了。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'blush', text: '你证明了他是对的——编程确实能改变一个人。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'genuine_smile', text: '你改变了 Nene——让她知道了什么是心跳。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'genuine_smile', text: '改变了 Yoshino——让她接受了不完美。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'genuine_smile', text: '改变了 Ayase——让她找到了比胜利更重要的东西。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'genuine_smile', text: '改变了 Kanna——让她的世界不再只有代码和星空。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'vulnerable', text: '也改变了我。' },
  { type: 'narration', text: '她伸出手，轻轻碰了碰最中心那台服务器的外壳。' },
  { type: 'narration', text: '金色瞳孔映着蓝绿色的光。像是两颗星星沉入了数字的海洋。' },
  { type: 'dialogue', speaker: 'murasame', expression: 'genuine_smile', text: '以后……这个地方由你和我一起守护。可以吗？' },
  { type: 'dialogue', speaker: 'murasame', expression: 'blush', text: '——这是命令，不是商量。笨蛋。' },
  { type: 'monologue', text: '（在数字星海的中心，两个人的手牵在了一起。）' },
  { type: 'monologue', text: '（这不是终点。这是新的起点——）' },
  { type: 'monologue', text: '（属于我们所有人的 Source Code。每一行代码都通向真理。每一个人都值得拥有心跳。）' },
  { type: 'monologue', text: '（Alethicode——以代码照亮真理。）' },
  { type: 'monologue', text: '（原来这个名字的意义，不只是学校的铭牌。它是创始人留下的信念。）' },
  { type: 'monologue', text: '（而现在——这份信念由我们来继承。）' },
  { type: 'cg', id: 'murasame_true_end' },
  { type: 'ending', endingType: 'true', route: 'murasame', title: 'Source Code',
    text: '揭开 Alethicode 学园的秘密。\n代码连接了所有人的心——这是最美的源代码。\n\n「以代码照亮真理。」——创始人的信念，由你们继承。\n\n—— 全线完结 · 感谢游玩 ——' }
]

export { murasame_good as routeMurasameGood, murasame_normal as routeMurasameNormal, murasame_true as routeMurasameTrue }
